export default {
    'USER_ADD_BOOK_TO_FAVORITES': 'USER_ADD_BOOK_TO_FAVORITES',
    'USER_REMOVE_BOOK_FROM_FAVORITES': 'USER_REMOVE_BOOK_FROM_FAVORITES',
    'USER_GET_BOOKS_FAVORITES': 'USER_GET_BOOKS_FAVORITES',

    'USER_GET_ACCOUNT_SETTINGS': 'USER_GET_ACCOUNT_SETTINGS',
}