export default {
    'BOOKS_FETCH': 'BOOKS_FETCH',
    'BOOKS_FETCH_BOOK_BY_ID': 'BOOKS_FETCH_BOOK_BY_ID',
    // 'BOOKS_ADD_TO_FAVORITES': 'BOOKS_ADD_TO_FAVORITES',
    // 'BOOKS_REMOVE_FROM_FAVORITES': 'BOOKS_REMOVE_FROM_FAVORITES',
    // // 'BOOKS_UPDATE_FAVORITES': 'BOOKS_UPDATE_FAVORITES',
    // 'BOOKS_GET_FAVORITES': 'BOOKS_GET_FAVORITES',
}