export default {
    'AUTH_LOGIN': 'AUTH_LOGIN',
    'AUTH_REGISTER': 'AUTH_REGISTER',
    'AUTH_SET_LOCAL_USERDATA': 'AUTH_SET_LOCAL_USERDATA',
    'AUTH_GET_LOCAL_USERDATA': 'AUTH_GET_LOCAL_USERDATA',
}